
services:
  builder:
    environment:
      - BR2_EXTERNAL=/app
      - BR2_DL_DIR=/app/buildroot-package-cache
    build:
      context: .
      args:
        UID: "${MY_UID:-1000}"
        GID: "${MY_GID:-1000}"
    volumes:
      - ..:/app
    working_dir: /app
    command: bash -c "echo 'Run `make shell`'"
