#cloud-config

# Add Docker's Ubuntu repository.
apt:
  sources:
    docker.list:
      # Part of this example comes from https://stackoverflow.com/a/62540068
      source: deb [arch=arm64] https://download.docker.com/linux/ubuntu $RELEASE stable
      # Key ID can be found with 'gpg --show-keys <(curl -s https://download.docker.com/linux/ubuntu/gpg)'
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 

# Update the list of packages available online
package_update: true
# Upgrade all installed packages
package_upgrade: true

# Install docker & other utilities
packages:
  - apt-transport-https
  - bc
  - btop
  - build-essential
  - ca-certificates
  - containerd.io
  - cpio
  - curl
  - docker-buildx-plugin
  - docker-ce
  - docker-ce-cli
  - docker-compose-plugin
  - file
  - golang-go
  - gnupg-agent
  - jq
  - less
  - libncurses-dev
  - libcrypt-dev   
  - pax-utils
  - python3
  - python3-pip
  - python3-yaml
  - rsync
  - software-properties-common
  - unzip
  - vim
  - wget

groups:
  - docker: [ubuntu]

write_files:
- path: /etc/profile.d/10_buildroot_env.sh
  content: |
    export BR2_EXTERNAL=$HOME/just_enough
    export BR2_DL_DIR=$HOME/just_enough/buildroot-package-cache
  permissions: '0644'
  owner: 'root:root'
  defer: true
