[global]
   # Basic Identification
   workgroup = WORKGROUP
   server string = JustEnough Samba Appliance
   server role = standalone server

   # User auth backend are local files managed by smbpasswd
   security = user

   # Min protocol is compatible with Win8 & MacOS Yosemite
   # Client should negotiate protocol
   server min protocol = SMB3_00
   
   # Hide add printer wizard from windows clients
   show add printer wizard = no
      
   # Guest account behavior, requires valid PW to access any share.
   guest account = nobody
   map to guest = bad user

   # Disable Printing Subsystem
   load printers = no
   printing = bsd
   printcap name = /dev/null
   disable spoolss = yes

   # Container Logging to STDOUT to let container engine manage logs
   log level = 1
   logging = stdout

   # Enable extended attributes on share for TimeMachine
   ea support = yes

   # Force UTF-8 Character sets for local posix paths
   unix charset = UTF-8
   dos charset = ascii

   # MacOS/Apple VFS Extensions
   # Settings taken from: 
   #    - https://wiki.samba.org/index.php/Configure_Samba_to_Work_Better_with_Mac_OS_X
   #    - https://www.samba.org/samba/docs/current/man-html/vfs_fruit.8.html
   #    - https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html
   vfs objects = catia fruit streams_xattr
   fruit:aapl = yes
   fruit:model = MacSamba
   fruit:nfs_aces = no
   fruit:veto_appledouble = no
   fruit:wipe_intentionally_left_blank_rfork = yes
   fruit:delete_empty_adfiles = yes
   fruit:metadata = stream
   fruit:encoding = native

# Example Timemachine Share. Uncomment and modify to enable.
# Make sure paths exist inside container or as external mounts
# Make sure users and groups exist by updating samba_groups and samba_secrets
#
# [TimeMachine_Bob]
#   path = /srv/timemachine/bob
#   comment = macOS TimeMachine Target for Bob
#   writeable = yes
#   browsable = yes
#   guest ok = no
#   valid users = bob
#   fruit:time machine = yes
#   fruit:time machine max size = 500G

# Example Network Data Share. Uncomment and modify to enable.
# Valid users are everyone in the data_share_group defined with the samba_groups file
#
# [MYDATA]
#    path = /srv/mydata
#    comment = General Storage
#    writeable = yes
#    browsable = yes
#    guest ok = no
#    valid users = @data_share_group
