forward-zone:
  name: "."
  forward-addr: 1.1.1.1

server:
    # Set verbosity level (0-5)
    verbosity: 2
    do-daemonize: no
    interface: 0.0.0.0
    port: 53
    access-control: 0.0.0.0/0 allow
    
    # Enable specific query/reply logging
    log-queries: yes
    log-replies: yes
    
    # Optional: Log to a specific file instead of syslog
    use-syslog: no
    log-time-ascii: yes

