server:
    verbosity: 2
    do-daemonize: no
    interface: 0.0.0.0
    port: 53
    access-control: 0.0.0.0/0 allow
    
    log-queries: yes
    log-replies: yes
    use-syslog: no
    log-time-ascii: yes

    # Absolute paths inside the container
    root-hints: "/etc/unbound/root.hints"
    auto-trust-anchor-file: "/etc/unbound/get-dnssec-root.key"
