name: Build Appliances 2

on:
  workflow_dispatch:
    inputs:
      buildroot_tag:
        description: 'Kitchen Sink Tag to consume'
        required: true
        default: '2026.02.1'

jobs:
  build-appliance:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "stub"

