name: Build Busybox
on:
  push:
     branches: [ main ]
     
jobs:
  build_busybox:
     runs-on: ubuntu-latest
     steps:
     - name: set ENV
       run: echo "NOW=$(date --rfc-3339=date)" >> "$GITHUB_ENV"
     - name: Checkout REPO
       uses: actions/checkout@v2
       with:
          submodules: recursive
     - name: Cache Dependencies
       uses: actions/cache@v2
       id: busybox_buildroot_cache
       with:
         path: /tmp/build
         key:  ${{ runner.os}}-make-${{ hashFiles('*build*') }}
         restore-keys: |
            ${{ runner.os }}-make
     - name: Build Busybox RootFS
       run: |
         export BR2_EXTERNAL=$GITHUB_WORKSPACE
         make O=/tmp/build -C ./buildroot container_busybox_defconfig
         make O=/tmp/build -C ./buildroot all
         make O=/tmp/build -C ./buildroot external-deps  | egrep -v 'Entering directory|Leaving directory' | sort > /tmp/package-list 
     - name: Upload RootFS
       uses: actions/upload-artifact@v2
       with:
          name: busybox_rootfs.${{ env.NOW }}.tgz
          path: /tmp/build/images/rootfs.tar.gz
     - name: Upload Package-List
       uses: actions/upload-artifact@v2
       with:
          name: package-list
          path: /tmp/package-list

